name: Latest blog post workflow

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull Dev.to and Medium posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: |
            https://dev.to/feed/zainulabdeenofficial
            https://medium.com/feed/@zu4425
          max_post_count: 5
          remove_duplicates: true
