name: Latest blog post workflow

on:
  schedule:
    - cron: '0 * * * *' # Every hour
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull in Medium and Dev.to posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: |
            https://dev.to/feed/zain_ulabdeen_6b0c7f5e43
            https://medium.com/feed/@zu4425
          max_post_count: 20
          remove_duplicates: true
          prioritise_latest: true
          disable_webhook: true

